### ISSUE TITLE
invalid parameter error in melodic

### ISSUE THREAD

**Issue by yuchengz279** [issaiass/jetbot_diff_drive#1] opened 2020-10-30 16:02 UTC
encountered error:
>Invalid parameter "ixz"
when instantiating macro: inertia (/catkin_ws/src/jetbot_diff_drive/urdf/includes/gazebo/inertias.xacro)
instantiated from: cuboid_inertia (/catkin_ws/src/jetbot_diff_drive/urdf/includes/gazebo/inertias.xacro)
in file: /catkin_ws/src/jetbot_diff_drive/urdf/includes/parts/chassis.xacro
included from: /catkin_ws/src/jetbot_diff_drive/urdf/jetbot.xacro
RLException: while processing /catkin_ws/src/jetbot_diff_drive/launch/gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/catkin_ws/src/jetbot_diff_drive/urdf/jetbot.xacro']] returned with> code [2]. 

There is something wrong with the  macros defined in the file "inertias.xacro" that the system cannot load the parameters.

Had to remove all inertia description in the part files to avoid this error. Then Rviz load works fine, but when loading Gazebo the model of the robot cannot be loaded, error reports that

>the robot has a joint called"lt_wheel_joint", which is not in the model.

I am running on ROS melodic on Ubuntu 18.04

**Comment by issaiass** [comment] 2020-10-30 17:48
Sorry for that. 

I am using ROS Noetic and everything goes fine, i have no error at all.

Also installed the full version of ROS

ROS Noetic in Ubuntu 20.04 LTS over Oracle VirtualBox

**Comment by issaiass** [comment] 2020-10-30 19:16
Did you tried state_publisher in type instead of robot_state_publisher in the type?

**Comment by yuchengz279** [comment] 2020-11-04 13:58
I switched to 20.04 with ROS Noetic and it is fine now. I think the problem is caused by different grammer rules for xacro files in different ROS versions. Thanks!

**Comment by issaiass** [comment] 2020-11-04 18:33
Good to know, check the repository for updates and comments.  I ported the realsense and pointcloud to aid in navigation.

Also i am planning to add a lidar in the sim too.

I will close the issue.

**Closed as completed** 2020-11-04 18:33 UTC

**Comment by techapostle** [comment] 2022-07-02 20:36
@issaiass Hello and sorry for reviving a dead issue. I'm trying to run this on an actual [robot](https://www.waveshare.com/jetbot-2gb-ai-kit-for-aws.htm), which is only supported via its [Ubuntu 18.04 image](https://jetbot.org/master/software_setup/sd_card.html). The problem is this version of Ubuntu only supports ROS up to its Melodic release. I'd be grateful if you could give me some insight towards alternative parameters that can be used in place, so that I can run this on Melodic instead of Noetic.
Thanks.

**Comment by issaiass** [comment] 2022-07-04 06:13
Sure, probably you could use with another ROS version and the problems will be specific, just tell me what you find.

________________________________
De: Kian Dadkhah ***@***.***>
Enviado: sábado, 2 de julio de 2022 3:36 p. m.
Para: issaiass/jetbot_diff_drive ***@***.***>
Cc: Rangel Isaías Alvarado Walles ***@***.***>; Mention ***@***.***>
Asunto: Re: [issaiass/jetbot_diff_drive] invalid parameter error in melodic (#1)


@issaiass<https://github.com/issaiass> Hello and sorry for reviving a dead issue. I'm trying to run this on an actual robot<https://www.waveshare.com/jetbot-2gb-ai-kit-for-aws.htm>, which is only supported via its Ubuntu 18.04 image<https://jetbot.org/master/software_setup/sd_card.html>. The problem is this version of Ubuntu only supports ROS up to its Melodic release. I'd be grateful if you could give me some insight towards alternative parameters that can be used in place, so that I can run this on Melodic instead of Noetic.
Thanks.
